<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>cccg-dispatch</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\..\artifacts\cccg-dispatch\win-x64-full\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CCCG.Core\CCCG.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="ModelContextProtocol" Version="0.4.0-preview.3" />
  </ItemGroup>
</Project>
