<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CCCG.Core\CCCG.Core.csproj" />
    <ProjectReference Include="..\..\src\CCCG.Monitor\CCCG.Monitor.csproj" />
    <ProjectReference Include="..\..\src\CCCG.Host\CCCG.Host.csproj" />
  </ItemGroup>
</Project>
